server:
  port: 8111
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  application:
    name: auth-service
  profiles:
    active: @activeEnv@

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml # 扫描类路径下mapper下的xml文件
  global-config:
    banner: false   # 不展示mybatis-plus自带的banner
    db-config:
      id-type: assign_id  # 设置数据库主键用雪花算法生成